# Site settings
title: Task Storage
email: mg222ym@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Website that stores assignments in the course Client-based Web programming (creating applications for the web browser) at Linnaeus university in Sweden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  margvo
twitter_username: orksofta

# a template URL where dynamic elements are represented by colon-prefixed keywords
permalink: /:categories/:title

# navigation links (as tutorial video "Building Static Websites With Jekyll. Configuration" suggests on https://webdesign.tutsplus.com/courses/building-static-websites-with-jekyll)
links:
 - title: about
   url: /about
 - title: assignments
   url: /assignments
 - title: blog
   url: /blog
 - title: contact
   url: /contact

# Build settings
markdown: kramdown
